---
title: "For researchers"
author: ""
output: 
  html_document:
      toc: true
      toc_depth: 3
      toc_float: true
      theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Request to Collaborate  
We welcome collaborations with external researchers.  If you are interested in forming a collaboration with one or more of the VED PIs, please read our **[Collaboration terms and Conditions](https://docs.google.com/document/d/17fI4j78OYshcBxxvp2Wq5LgLeruCDTBwfFIQkOC0Qsc/edit?usp=sharing)** and then complete the **[Request to Collaborate](https://docs.google.com/forms/d/e/1FAIpQLSf6yBxC_A4G2luIqD5hABHwIurH9Tu19ooL4-nnIOQvU7XtuQ/viewform?usp=sf_link)** form.  
\

### Request early access to data  
Data is embargoed for 6 months from time of collection to ensure adequate processing and initial analysis by the Project Team.  Occasionally, access to data by external researchers will be granted provided the research questions to be addressed do not overlap substantially with those of the project PIs and their teams.  To **[Request Early Access to the data](https://docs.google.com/forms/d/e/1FAIpQLSdk66Lk9jg6egBP44Nl2tK5UrzobiF5hJxvzFb_wVCDybZwRw/viewform?usp=sf_link)**, complete and submit the linked form.  
\

### Access Data  
Check back soon for more information   
\    

### Software  
Check back soon for more information    
\


### Acknowledgement of funding  
Please acknowledge the Visual Experience Database and its funding source on all publications and presentations arising from work with the data and/or software available from this page by referencing  
*National Science Foundation award #1920896 - RII Track-2 FEC: The Visual Experience Database: A Large-Scale Point-of-View Video Database for Vision Research*

