---
title: "Big Data Summer School"
subtitle: "Reno, NV  July 6-10, 2020"
author: ""
output: 
  html_document:
      toc: true
      toc_depth: 3
      toc_float: true
      theme: cerulean

---

<div style="text-align: justify">
We are currently accepting applications for the inaugural Big Data Summer School to be held  July 6-10, 2020 at the University of Nevada, Reno. The aim of the summer school is to provide undergraduate and early graduate students with the foundational skills necessary to work with the types of large-scale datasets that are common in 21st century scientific research. 

In this five-day immersive learning event, students will learn facility with the command line, foundations of networking, working with common text editors such as Nano and Vim, package management, and version control. The summer school will also include guest lectures by leading researchers who have leveraged large-scale data for scientific advancement.  
\

The summer school is supported by an NSF EPSCoR Track-II Research Infrastructure Improvement Program grant and will be led by the PIs:   
* Michelle Greene, PhD (Bates College)  
* Ben Balas, PhD (North Dakota State University)  
* Paul MacNeilage, PhD (Univ. of Nevada, Reno)  
* Mark Lescroart, PhD (Univ. of Nevada, Reno). 
\
\

### Eligibility  
Per NSF EPSCoRE funding requirements, to be eligible for the Big Data Summer School, you must be a resident of one of the following EPSCoRE states: Alabama, Alaska, Arkansas, Delaware, Guam, Hawaii, Idaho, Iowa, Kansas, Kentucky, Louisiana, Maine, Mississippi, Montana, Nebraska, Nevada, New Hampshire, New Mexico, North Dakota, Oklahoma, Puerto Rico, Rhode Island, South Carolina, South Dakota, Vermont, US Virgin Islands, West Virginia, or Wyoming. By applying, you certify that you intend to attend the entire summer school if your application is accepted.

We encourage submissions from undergraduate students and early-stage graduate students who have not had extensive computer science training. We especially encourage the application of students whose identities have historically been under-represented in computational science.  
\
\

### Financial Support  
Financial support for most costs associated with travel, lodging, and subsistence for the duration of the conference will be provided for all students selected for participation in the Big Data Summer School.  
\
\

### Applications  
To apply for the Big Data Summer School, please complete this [application form](https://docs.google.com/forms/d/e/1FAIpQLSdBWa9--esGaGVGH20jkqpWrzqiYLBGxz44TLAEvhZLLmHYSw/viewform?usp=sf_link).  
\
\

### Review and Selection Process  
All applications meeting the eligibility requirements will be placed in a random lottery for available spots.  
\
\

### Important Dates  
* April 1, 2020: Applications due  
* April 15, 2020: Notification of acceptance  
* July 6-10, 2020: Workshop  
\
\

### Contact  
For more information, please contact:

Maggie Diamond-Stanic  
Grant Coordinator  
Bates College  
mdiamond@bates.edu
</div>

